### ISSUE TITLE
Android: ability have multiple (or toggle) auth0Domain on manifestPlaceholders at runtime?

### ISSUE THREAD

**Issue by VladSVAssets** [auth0-samples/auth0-android-sample#109]
Hello,

I am currently following this documentation: [Android: Login](https://auth0.com/docs/quickstart/native/android)

My question concerns the build.gradle file for the app.

// —> Add the next line
manifestPlaceholders = [auth0Domain: “@string/com_auth0_domain”, auth0Scheme: “demo”]
// <—

I also see that these values, per documentation:

The placeholders are used internally to define an intent-filter that captures the authentication callback URL.

I have a situation where I must toggle the domain between (or have it from the start to accept) the development and production environments. Auth0 is unable to complete authentication on my Android app because those values are dynamic, and from the documentation the domain is a static value with only one url domain accepted.

The only “solution” I’ve found is to set the host value to use a wildcard (*.mydomain.com), but this does not work too well for my domains and it does not seem to be a safe implementation.

**Comment by VladSVAssets** [comment]
I want to mention that I need to toggle on the same build (not separate depending on the flavor for example), because on my application the user can swap environments at runtime.

**Comment by alexandrudumbravan-nutmeg** [comment]
Hello

For what it's worth there is a workaround to the issue.

Add the Auth0 Redirect to the manifest and declare different placeholders like the following example:

 <activity
            android:name="com.auth0.android.provider.RedirectActivity"
            android:exported="true"
            tools:node="replace">
            <intent-filter
                android:autoVerify="true"
                tools:targetApi="m" >
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="${domain1}"
                    android:pathPrefix="/android/${applicationId}/callback"
                    android:scheme="${scheme1}" />

                <data
                    android:host="${domain2}"
                    android:pathPrefix="/android/${applicationId}/callback"
                    android:scheme="${scheme2}" />
            </intent-filter>

        </activity>

This allows you to link multiple callbacks from different environments
