### ISSUE TITLE
Looking For the java code for implementation of Auth0 for user login in android app

### ISSUE THREAD

**Issue by shubhangimuley** [auth0-samples/auth0-android-sample#143]
Working on android project.
using Auth0 for Login in java android application

**Comment by poovamraj** [comment]
Hi @shubhangimuley, You can find the Java sample here - https://github.com/auth0-samples/auth0-android-sample/tree/master/00-Login

**Comment by shubhangimuley** [comment]
> Hi @shubhangimuley, You can find the Java sample here - https://github.com/auth0-samples/auth0-android-sample/tree/master/00-Login
Thank you for Your quick response @poovamraj but in this I'm facing  the issue while getting the user profile information .
