### ISSUE TITLE
Sample 07 - Button set out of the screen

### ISSUE THREAD

**Issue by nnats** [auth0-samples/auth0-android-sample#29]
Running this project on a 5.5-inch screen with Android 6.0.1 the activity_main.xml place the "App Settings" button out of the screen, this button has marginTop of 100dp wich may cause the problem if the content above has too much height. 

![image](https://cloud.githubusercontent.com/assets/20141842/21971230/6740e774-db8d-11e6-85ee-1addc189b102.png)

Steps to reproduce:
- Download the sample app for authorization.
- Compile it and run it on Android Studio.
- Login with a user given the role of admin.

**Comment by jimmyjames** [comment]
Closing this issue as it is pretty old, and the sample has changed since reporting. If you're still experiencing the issue, please reopen or create a new issue, and include any updated or additional information.
