### ISSUE TITLE
Cannot GET /android on specific "facebook" connection

### ISSUE THREAD

**Issue by vishal-i4gs** [auth0-samples/auth0-android-sample#49]
On the WebAuthProvider part if I add .withConnection("facebook") and my chrome browser logs into facebook for the first time, it works fine and redirects to my app but if my browser is already logged into facebook and I try authlogin, the browser does not redirect to the app, It tells Cannot GET/ android.

**Comment by lbalmaceda** [comment]
@vishal-i4gs That's weird.. but I could reproduce it. The issue is probably in the auth0.android SDK. While we investigate, either downgrade to version 1.8.0 which is not using Chrome Custom Tabs or override the RedirectActivity's intent-filter using a custom scheme (follow [this doc](https://github.com/auth0/auth0.android#authentication-with-hosted-login-page)). Keep in mind that changing the scheme will impact in i) manually adding the intent-filter, overriding the RedirectActivity's, ii) changing the callback URL in your client's dashboard and iii) calling `.withScheme("yourscheme")` on the WebAuthProvider builder.

**Comment by vishal-i4gs** [comment]
@lbalmaceda I actually downgraded the version to 1.8.0 and it seems to be fine in that and would like to know why the current example app is still running 1.8.0 instead of the latest one.

**Comment by x-cray** [comment]
Spent half the day until I found this issue. Setting custom scheme works well for me.

**Comment by iX21Mobile** [comment]
Settings a custom scheme doesn't seem to work anymore... I get a blank page instead of the error and I'm not able to log in.
I reproduce this behavior on different Android version. I use Lock : com.auth0.android:lock:2.8.0
Did anyone encounter the same issue ?

**Comment by iX21Mobile** [comment]
Settings a custom scheme doesn't seem to work anymore... I get a blank page instead of the error and I'm not able to log in.
I reproduce this behavior on different Android version. I use Lock : com.auth0.android:lock:2.8.0
Did anyone encounter the same issue ?

**Comment by Wayneio** [comment]
@iX21Mobile I've just solved this issue myself. You have to set a custom scheme in 3 places:

1) In the build.gradle file - `manifestPlaceholders = [auth0Domain:  "shoutapp.eu.auth0.com", auth0Scheme: "XXX"],`
2)The lock initialisation code -   `lock = Lock.newBuilder(auth0, callback).withScheme("shout")`
3) In your Auth0 Dashboard, under callback urls like `XXX://domain.eu.auth0.com/android/com.domain.app/callback`,

If you use an old version of lock, you also need to add a data element to the intent-filter in the manifest:
     ```
 <data
        android:host="@string/com_auth0_domain"
        android:pathPrefix="/android/${applicationId}/callback"
        android:scheme=“XXX” />
```

**Comment by lbalmaceda** [comment]
All this is already explained in the [sdk library readme](https://github.com/auth0/Auth0.Android#authentication-with-hosted-login-page), in the [lock library readme](https://github.com/auth0/lock.android#android-app-links---custom-scheme) and in the [android quickstarts introduction](https://auth0.com/docs/quickstart/native/android). If you run into any issues don't hesitate opening a new issue in the corresponding library repo so we can track it, or contact our amazing team at https://support.auth0.com.

**Comment by NivaLevy** [comment]
@Wayneio adding- scheme must be low case string

**Comment by sharukhmohammed** [comment]
I have used the scheme as a lower case 'xxx' and it works fine but it throws me up a new error. 


```
E/OAuthManager: Received state doesn't match. Received VikZhSyOD0MBxkiPG7swzaQsc2yAuM6s2Y3jn_m3yfU but expected On7vaXLWhWslEoh8ly0e9eFxhboZktfjyh_MXk3nULo
W/System.err: com.auth0.android.authentication.AuthenticationException: An error occurred when trying to authenticate with the server.
W/System.err:     at com.auth0.android.provider.OAuthManager.assertValidState(OAuthManager.java:187)
W/System.err:     at com.auth0.android.provider.OAuthManager.resumeAuthorization(OAuthManager.java:120)
W/System.err:     at com.auth0.android.provider.WebAuthProvider.resume(WebAuthProvider.java:389)
W/System.err:     at com.auth0.android.provider.AuthenticationActivity.deliverSuccessfulAuthenticationResult(AuthenticationActivity.java:126)
W/System.err:     at com.auth0.android.provider.AuthenticationActivity.onResume(AuthenticationActivity.java:85)
W/System.err:     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1413)
W/System.err:     at android.app.Activity.performResume(Activity.java:7366)
W/System.err:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3816)
W/System.err:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3856)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err:     at android.os.Looper.loop(Looper.java:201)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6806)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

I cannot find any docs/discussions nor have any leads. Any help would be appreciated.

**Comment by paixols** [comment]
If using web WebAuthProvider, we also need to include:
```
WebAuthProvider.withScheme("XXX")
```
