### ISSUE TITLE
Cannot GET /android/com.auth0.samples/callback

### ISSUE THREAD

**Issue by Amialc** [auth0-samples/auth0-android-sample#51]
(AUTH-4143)
After login, I've received error [Cannot GET /android/com.auth0.samples/callback](https://user-images.githubusercontent.com/1114365/28204147-68fd0018-6885-11e7-8ba2-255973ab6ce5.png)

**Comment by lbalmaceda** [comment]
Dupe https://github.com/auth0-samples/auth0-android-sample/issues/49
