### ISSUE TITLE
Can id_token be returned in HS256 instead of RS256?

### ISSUE THREAD

**Issue by winseyli** [auth0-samples/auth0-android-sample#54]
The id_token returned is always in RS256. Is it possible to be in HS256 signature algorithm?

**Comment by lbalmaceda** [comment]
That depends on your client's token signing configuration. See [here](https://auth0.com/docs/apis#signing-algorithms) for more info, and please use [other channels](https://support.auth0.com) for support as this is not one of them.
Cheers.
