### ISSUE TITLE
Outdated Version library used from Auth0.Android

### ISSUE THREAD

**Issue by EngelsTechAid** [auth0-samples/auth0-android-sample#55]
In the `build.gradle` app there's a reference to the `com.auth0.android:auth0` ~decrecated~outdated as shown here:

![2017-10-18 17_02_14-00-login - c__users_engels medina_desktop_techaid_auth0android_00-login - app](https://user-images.githubusercontent.com/32913317/31742622-273698f0-b426-11e7-8b55-e515aaad8f23.png)

Which in [Auth0.Android Repo](https://github.com/auth0/Auth0.Android) exists the `com.auth0.android:auth0:1.11.0` version.

**Comment by jimmyjames** [comment]
Build file has been updated to use latest 1+ version, closing this issue. Thanks for reporting!
