### ISSUE TITLE
Mobile Android: No info in readme

### ISSUE THREAD

**Issue by paulioceano** [auth0-samples/auth0-android-sample#59]
The README.md file doesn't have any information about the sample project.

![image](https://user-images.githubusercontent.com/15818783/34359001-f3d6a938-ea2a-11e7-9429-71e28e5b0c19.png)
![image](https://user-images.githubusercontent.com/15818783/34359039-02c98258-ea2b-11e7-969c-99846ce03988.png)
![image](https://user-images.githubusercontent.com/15818783/34359066-3646ec92-ea2b-11e7-9060-f5f365c6c0de.png)
![image](https://user-images.githubusercontent.com/15818783/34359068-3f5aa81e-ea2b-11e7-8a47-9950c2f7d01d.png)
![image](https://user-images.githubusercontent.com/15818783/34359079-49c7fd24-ea2b-11e7-9e5a-216f64750ea9.png)
![image](https://user-images.githubusercontent.com/15818783/34359085-518afde0-ea2b-11e7-9473-28f3d8a73f1c.png)

**Comment by lbalmaceda** [comment]
That's true. The idea is that you follow the steps on the Quickstart article linked in the Readme in order to run the sample. Maybe this wasn't that clear? I'm curious, have you read the article first or just skipped it? What are your expectations for the Readme contents?
Cheers 🎉

**Comment by paulioceano** [comment]
Yes, I have read the article and follow the steps successfully.

In the README.md is not quite clear what you have to do, and normally in all the Auth0's sample projects this file has instructions to run the sample code, e.g: 

- https://github.com/auth0-samples/auth0-angular-samples/tree/master/01-Login
- https://github.com/auth0-samples/auth0-php-api-samples/tree/master/01-Authenticate-RS256
-

**Comment by lbalmaceda** [comment]
That's fair! Thanks for the feedback. I think we should at least show how to configure the auth0 parameters and run the project. I'll add a task to fix it in the next iteration.

**Comment by aaguiarz** [comment]
@lbalmaceda can you add the content from one, so we can then replicate it to the rest?

**Comment by lbalmaceda** [comment]
@aaguiarz I've already done this https://github.com/auth0-samples/auth0-android-sample/pull/61/files. I'll close the issue
