### ISSUE TITLE
Logout button wrong tag

### ISSUE THREAD

**Issue by rafanog** [auth0-samples/auth0-android-sample#63]
On the "user profile" sample, the logout button's currently tagged as "Login again" instead of logout:
![image](https://user-images.githubusercontent.com/15782359/38142716-77b7e878-340b-11e8-83e5-dee2f1d9ddb0.png)

**Comment by luminousAvocado** [comment]
Is there any way to do logout in Xamarin.Forms, rather than platform specific (Android, iOS)?
