### ISSUE TITLE
Cannot GET /android callback issue

### ISSUE THREAD

**Issue by kaleempeeroo** [auth0-samples/auth0-android-sample#77]
Hi. I tried the steps mentioned:
https://github.com/auth0-samples/auth0-android-sample/issues/65
https://github.com/auth0-samples/auth0-android-sample/issues/49
but still cannot get callback from the android app. Plz advise.

**Comment by lbalmaceda** [comment]
I'll close this one. Please, if it's the same issue let's keep the conversation in there. 

Can you share a vanilla sample to reproduce the error?

**Comment by kaleempeeroo** [comment]
Thanks.
Replied #65
