### ISSUE TITLE
Android SDK with PCKE

### ISSUE THREAD

**Issue by etanxing** [auth0-samples/auth0-android-sample#83]
Hi There,

In https://auth0.com/docs/flows/concepts/auth-code-pkce it said `The easiest way to implement the Authorization Code Flow with PKCE is to follow our Mobile/Native Quickstarts`. so I followed this repo but got `com.auth0.android.authentication.AuthenticationException: Could not verify the ID token` error.

Here is my config:
```
WebAuthProvider.login(auth0)
    .withScheme("https")
    .withAudience(String.format("https://%s/userinfo", getString(R.string.com_auth0_domain)))
    .start(this, loginCallback);
```
Thanks

**Comment by lbalmaceda** [comment]
There should be a `cause` associated with that `exception` instance, see if you can get it with the debugger and share it here. It's probable that your application is not configured as OpenID compliant. Check the dashboard, application settings, advanced settings, OAuth, and see if the OpenID / OIDC switch is ON.

**Comment by exerdra** [comment]
I was seeing this error when my device date didn't match up with the actual time. Make sure your device is set to the `Use network provided time property` and it should work.

**Comment by lbalmaceda** [comment]
Closing until more info is provided. If you still need help, please re-open.
