### ISSUE TITLE
Android applications targeting SDK 30+ require additional manifest attributes

### ISSUE THREAD

**Issue by undermark5** [auth0-samples/auth0-android-sample#88]
Google has made changes in the way that applications are allowed to interact with the package manager. They are no longer free to query for any installed packages out of the box when targeting SDK 30+. Additional manifest attributes are required in order to the application to be able to query for an application that can handle the android.intent.action.VIEW intent with scheme https (in other words, withtout these attributes, the auth0 sdk will say that there is no installed browser even when there is).

```xml
<manifest>
 <-- ... -->
    <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="https" />
        </intent>
    </queries>
 <-- ... -->
</manifest>
```

see https://developer.android.com/preview/privacy/package-visibility for more information

Either the guide needs to be updated, or the combined manifest needs to result in these attributes automatically being applied

**Comment by undermark5** [comment]
Unless this clarification has been added to the documentation, this is not complete and should not be closed.

**Comment by undermark5** [comment]
Unless this clarification has been added to the documentation, this is not complete and should not be closed.

**Comment by lbalmaceda** [comment]
Apologies we missed this and thanks for the catch. The library has since been updated to include this in the internal AndroidManifest file, which ends up merged with your application's manifest. You can see that here https://github.com/auth0/Auth0.Android/blob/main/auth0/src/main/AndroidManifest.xml#L34-L40.
